### ISSUE TITLE
`"docker"` or `"docker stats"` command is not available in Bitbucket Pipelines - No mention in the tutorial

### ISSUE THREAD

**Issue by ozmium** [cloudytuts/website#190]
**Describe the bug**
`"docker"` or `"docker stats"` command is not available in Bitbucket Pipelines

**To Reproduce**
1. Go to https://www.cloudytuts.com/tutorials/docker/how-to-check-memory-and-cpu-utilization-of-docker-container/
2. Read the tutorial
3. Try to apply it to a `yml` file for a CI build in Bitbucket Pipelines, which uses a Docker container to build some software
4. Add the command: `docker stats --no-stream` into your yml file somewhere

**Expected behavior**
1. The `docker stats --no-stream` should display some useful output about the memory and CPU usage of the current Docker container, when used in Bitucket Pipelines.

2. The tutorial should explicitly mention if the command will work in Bitbucket Pipelines or not (when using a Docker image).

**Actual behavior**
The Bitbucket Pipelines console output shows an error:

```
/opt/atlassian/pipelines/agent/tmp/bashScript2063228033524053020.sh: line 30: docker: command not found
```

The tutorial doesn't give any details about whether this command will work in [Bitbucket Pipelines](https://bitbucket.org/product/features/pipelines), or other CI services like [Github Actions](https://github.com/features/actions) or [GitLab CI/CD](https://docs.gitlab.com/ee/ci/)

**Desktop (please complete the following information):**
 - OS: Linux (any version) using a Docker container for CI builds
 - Browser: Not applicable

**Additional context**
The tutorial should say if the "docker" command will work when it's added to a YML file, for a CI/CD build script (for example in the `bitbucket-pipelines.yml` or `.gitlab-ci.yml` file, at the root of the project). If not, suggest some alternative commands that work, which are mentioned here:

* https://stackoverflow.com/questions/74892317/how-can-i-find-a-memory-leak-or-what-is-taking-up-so-much-memory-in-parceljs

**Comment by serainville** [comment]
The tutorial assumes the command is executed by an operator or shell script, and anything outside of those would be out of scope. If the command is being evoked from an automation system then documentation of that system should describe how it can be done within its processes. 

With that said, I believe there's an opportunity to cover the use case in question, and perhaps the scope of this tutorial should be expanded. Or, a new tutorial is written specifically to cover Bitbucket, Github, and Gitlab pipelines.

**Comment by ozmium** [comment]
Thanks for adding the info. The tutorial is much better now.

Consider adding in a reference for where you got these commands from:

https://github.com/cloudytuts/website/blob/c6de1ddcfcbc1219c7099ea11d189b908def1514/content/en/tutorials/docker/how-to-check-memory-cpu-utilization-of-container.md?plain=1#L68-L71

I believe they originally came from the Atlassian's "Troubleshooting Bitbucket Pipelines" guide here:

https://confluence.atlassian.com/bbkb/troubleshooting-bitbucket-pipelines-1141505226.html

**Comment by serainville** [comment]
Adding a references section to posts has been on my mind for awhile. This would be a good time to start.
